# Edit this settings before install
accounts:
  root-password: root
  username: alessandro
  password: password

settings:
  ntp: true
  keymap: it
  locale: en_US.UTF-8 UTF-8
  lang: en_US.UTF-8
  region: Europe
  location: Rome
  hostname: Matebook

packages:
  # Required packages
  - base
  - linux-lts
  - linux-firmware
  - grub
  - efibootmgr
  - networkmanager
  - base-devel
  - amd-ucode
  - vim
  - util-linux

  # Window Managment
  - xorg
  - kde-applications
  - plasma
  - plasma-wayland-session

  # You can add other stuff here

# Do not touch the following settings if you have used the `format.sh` script for partitioning.
partitions:
  efi: /dev/sda1
  linux: /dev/sda2

boot:
  efi-directory: /boot/efi
  bootloader-id: grub
  target: x86_64-efi
