partitions:
  efi: /dev/sda1
  linux: /dev/sda2

boot:
  efi-directory: /boot/efi
  bootloader-id: grub
  target: x86_64-efi

accounts:
  root-password: root
  username: alessandro
  password: password

settings:
  ntp: true
  keymap: it
  locale: en_US.UTF-8 UTF-8
  lang: en_US.UTF-8
  region: Europe
  location: Rome
  hostname: Matebook
  username: alessandro

packages:
  - base
  - base-devel
  - linux-lts
  - linux-firmware
  - amd-ucode
  - vim
  - grub
  - efibootmgr
  - networkmanager
  - util-linux
  - xorg
  - kde-applications
  - plasma
  - plasma-wayland-session
